export const SAVE_INFO_USER = 'SAVE_INFO_USER';
export const SAVE_INFO_USER_SUCCESS = 'SAVE_INFO_USER_SUCCESS';
export const SAVE_INFO_USER_ERROR = 'SAVE_INFO_USER_ERROR';

export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_ERROR = 'USER_LOGOUT_ERROR';

//________

export const SAVE_INFO_PET = 'SAVE_INFO_PET';
export const SAVE_INFO_PET_SUCCESS = 'SAVE_INFO_PET_SUCCESS';
export const SAVE_INFO_PET_ERROR = 'SAVE_INFO_PET_ERROR';

//________

export const ACCEPT_INTERESED = 'ACCEPT_INTERESED';
export const ACCEPT_INTERESED_SUCCESS = 'ACCEPT_INTERESED_SUCCESS';
export const ACCEPT_INTERESED_ERROR = 'ACCEPT_INTERESED_ERROR';

export const REJECT_INTERESED = 'REJECT_INTERESED';
export const REJECT_INTERESED_SUCCESS = 'REJECT_INTERESED_SUCCESS';
export const REJECT_INTERESED_ERROR = 'REJECT_INTERESED_ERROR';